version: '3.3'
services:
  redis:
    image: redis:7.0.12
    container_name: redis
    restart: always
    volumes:
      - 'redis_volume_data:/data'
    networks:
      - backend
    ports:
      - '6379:6379'
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    networks:
      - backend
    ports:
      - '8001:8001'
    volumes:
      - 'redis_insight_volume_data:/db'
networks:
  backend:
    external: true
volumes:
  redis_volume_data:
  redis_insight_volume_data: