version: '3.3'
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - backend
    ports:
      - '27017:27017'
    volumes:
      - './data/db:/data/db'
networks:
  backend:
    external: true